version: "1"

build:
  os: "CentOS"
  tools:
    python: "3.6.15"

python:
  install:
    - requirements: ./requirements.txt
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py
