[run_pipeline]
# PIPELINE_DIR set to path on local machine where SWEPT is installed
PIPELINE_DIR=/raid/scratch/wongj/mywork/3x2pt/SWEPT/

[redshift_distribution]
# Parameters to set n(z) redshift distribution for mock observation

# Minimum redshift
ZMIN=0.1
# Maximum redshift
ZMAX=0.6
# z_0 parameter to govern functional form of n(z) - see Eq. 44 in Wong+24
Z0=0.636
# beta parameter to govern functional form of n(z) - see Eq. 44 in Wong+24
BETA=1.5
# Resolution to sample galaxies
DZ=0.1
# No. galaxies to generate - must be written in scientific notation
NGAL=1e6

[create_nz]
# n(z) in table format to create map realisations of 3x2pt signal on the sky using Flask
NZ_TABLE_NAME=Raw_Galaxy_Sample_nz.txt
# No. redshift bins to decompose raw galaxy sample into. This should match the number of steps used to resolve the n(z), i.e (N_ZBIN = ZMAX=ZMIN/DZ). If N_ZBIN is more, this does not make sense; if N_ZBIN is less than this value the code will interpolate field information to 'fill in' the signal a intermediate redshift slices
N_ZBIN=5

[simulation_setup]
# Path to location on disk to save mock catalogues
SIMULATION_SAVE_DIR=/raid/scratch/wongj/mywork/XCORR/Fields_XCORR/Simulation/
# NSIDE of maps used to create observation
NSIDE=128
# Minimum ell to use to generate 3x2pt maps
INPUT_ELL_MIN=2.0
# Maximum ell to use to generate 3x2pt maps
INPUT_ELL_MAX=250.0
# No of catalogue realisations to simulate
REALISATIONS=50
# Plot 3x2pt maps at each redshift slice (YES) or not (NO). Generally leave to NO unless debugging - there will be a lot of files produced!
PLOT_MAPS=NO
# Path to survey mask used for observation
PATH_TO_MASK=/raid/scratch/wongj/mywork/3x2pt/Euclid_Masks/Euclid_DR1_128.fits

[compile_cat]
# Parameters to govern injection of uncertainties in simulated catalogue
#SIGMA_PHOT=0.05
#SIGMA_SHEAR=0.3
#CAT_PHOTO_Z_FRAC=0.05
#CAT_PHOTO_Z_SIGMA=0.1

# Standard deviation quantity describing Gaussian photo-z errors (see Eq. 46 in Wong+24)
SIGMA_PHOT=0.0
# Standard deviation quantity describing Gaussian shape noise (see Eq. 48 in Wong+24)
SIGMA_SHEAR=0.0
# Fraction of galaxies which will have catastrophic uncertainties in the galaxy redshift estimates (see Sect.4.6, Wong+24)
CAT_PHOTO_Z_FRAC=0.0
# Standard deviation quantity describing catastrophic photo-z uncertainty (see Eq. 46, 47 in Wong+24)
CAT_PHOTO_Z_SIGMA=0.0

[run_cosmosis]
# Path to CosmoSIS installation on disk
COSMOSIS_ROOT_DIR=/raid/scratch/wongj/cosmosis/
