[run_pipeline]
# PIPELINE_DIR set to path on local machine where SWEPT is installed
PIPELINE_DIR=/raid/scratch/wongj/mywork/3x2pt/SWEPT/

[inference_analysis_params]

# Path to location on disk where measured tomographic PCl bandpowers are saved (output by pcl_measurement/run_3x2pt_tomo_measurement.sh)
MEASUREMENT_SAVE_DIR=/raid/scratch/wongj/mywork/3x2pt/FINAL_DATA_l600/
# Name of txt file which contains redshift boundary info. of given tomographic configuration (as set in pcl_measurement/set_variables_3x2pt_measurement.ini). This does not need to be changed
NZ_TABLE_FILENAME=Observed_nz.txt
# Path to location of CosmoSIS installation on local machine
COSMOSIS_ROOT_DIR=/raid/scratch/wongj/cosmosis/
# Path to survey mask used for mock observation/simulation data
PATH_TO_MASK=/raid/scratch/wongj/mywork/3x2pt/Euclid_Masks/Euclid_DR1_128.fits
# Number of chains to run in parallel to set up grid for likelihood analysis. Dependent on no. CPUs on machine. If machine has N CPUs, N_CHAINS can be set to N-1
N_CHAINS=11

# Minimum ell used for maps to simulate catalogues in catalogue_sim.run_cat_sim.sh
INPUT_ELL_MIN=2.0
# Maximum ell used for maps to simulate catalogues in catalogue_sim.run_cat_sim.sh
INPUT_ELL_MAX=2000.0
# Minimum ell that NN PCl spectra are measured to from mock catalogue data
OUTPUT_ELL_MIN_NN=100.0
# Maximum ell that NN PCl spectra are measured to from mock catalogue data
OUTPUT_ELL_MAX_NN=600.0
# Minimum ell that NE PCl spectra are measured to from mock catalogue data
OUTPUT_ELL_MIN_NE=100.0
# Maximum ell that NE PCl spectra are measured to from mock catalogue data
OUTPUT_ELL_MAX_NE=600.0
# Minimum ell that EE PCl spectra are measured to from mock catalogue data
OUTPUT_ELL_MIN_EE=100.0
# Maximum ell that EE PCl spectra are measured to from mock catalogue data
OUTPUT_ELL_MAX_EE=1500.0
# No. tomographic bins used to characterise PCl data
N_ZBIN=1
# NSIDE used to generate maps for shear catalogue creation/measure PCl spectra
NSIDE=1024
# Minimum redshift of redshift range specified for tomographic PCl measurement
ZMIN=0.3
# Maximum redshift of redshift range specified for tomographic PCl measurement
ZMAX=2.7
# No. angular bandpowers used to characterise PCl measurement
N_BANDPOWERS=10
# Bandpower spacing. Should be 'log' for logarithmic spacing or 'lin' for linear spacing
BANDPOWER_SPACING=log
# Observation type: either '3X2PT' to consider constraints from a full 3x2pt analysis, or '1X2PT' to consider constraints for a shear-only or angular galaxy clustering-only analysis
OBS_TYPE=3X2PT
# If OBS_TYPE=1X2PT for a single component analysis, FIELD must be either 'N' for clustering, or 'E' for shear
FIELD=N
# No. galaxies in sample. Only useful for plottting purposes (not necessary for analysis)
NGAL=3e8

